---
title: "Beyer Orchard Layout (TREE TURNOVER)"
output:
  html_document:
    df_print: paged
    code_folding: "hide"
    theme: readable
---


```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggalt)
library(ggthemes)
library(RODBC)
library(RColorBrewer)
#########################################################################

# Connect to the database

#odbcDataSources()
connect <- odbcDriverConnect("Driver={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=D:/Users/Dr Roger Beyer/Desktop/CHESTNUTS/access_database/BeyerFarm.accdb")


treedata <- sqlQuery(connect, "select *
                     from 
                     Tree")

treevar <- sqlQuery(connect, "select * from TreeVariety")

treelocationdata <- sqlQuery(connect, "select * from TreeLocation")
treecommentdata <- sqlQuery(connect,"SELECT * from TreeComment where Line = 1")
treedata_joined <- inner_join(treedata, treelocationdata, by = "TreeLocationID")
treedata_joined_var <- inner_join(treedata_joined,treevar, by="TreeVarietyID")

odbcClose(connect)


#########################################################################

# find all trees in the field now




# find all trees in the field now

# Step 1:  select only necessary columns
trees_final <- treedata_joined_var %>%
  select(TreeLocationID, TreeID,Column, Row,TreeDeath, TreeDeathDate, TreePlantDate,TreeVarietyName,Pollinator,Transplant)
  

trees_final3 <- trees_final %>%
  filter(Column != 'ZZZ') %>%
  group_by(Column,Row) %>%
  summarise(tree_count = n_distinct(TreeID))

#########################################################################



trees_final3$Column <- factor(trees_final3$Column, levels = c("A","B","C","D","E","F",
                         "G","H","I","J","K","L",
                         "M","N","O","P","Q","R","S",
                         "T","U","V","W","X","Y","Z","AA",
                         "BB","CC","DD"))
```



<br>


```{r message=FALSE,warning=FALSE, fig.align="center", fig.width=18, fig.height=24}

trees_final3$Column <- factor(trees_final3$Column, levels = c("A","B","C","D","E","F",
                                                              "G","H","I","J","K","L",
                                                              "M","N","O","P","Q","R","S",
                                                              "T","U","V","W","X","Y","Z","AA",
                                                              "BB","CC","DD"))


columnlabs1 <- levels(trees_final3$Column)
columnlabs2 <- c("A","B","C","D","E","F",
                 "G","H","I","J","K","L",
                 "M","N","O","P","Q","R","S",
                 "T","U","V","W","X","Y","Z","AA",
                 "BB","CC","DD")


  ggplot(filter(trees_final3, Row > 58), aes(as.numeric(Column), Row)) + geom_tile(aes(fill = as.factor(tree_count)),colour = "white",size=2.2) +
  scale_fill_brewer(palette = "YlOrRd",type="seq") + 
  theme_minimal()  +
  scale_x_continuous(breaks = 1:length(columnlabs1),
                     labels = columnlabs1,
                     sec.axis = sec_axis(~.,
                                         breaks = 1:length(columnlabs2),
                                         labels = columnlabs2)) + 
  scale_y_continuous(sec.axis = dup_axis(),
                     breaks = round(seq(0, max(trees_final3$Row), by = 5),1),
                     minor_break = seq(0,max(trees_final3$Row),5)) + 
  theme(legend.position="top") +
  theme(axis.text.x = element_text(size =22),
        axis.text.y = element_text(size=22),
        legend.text = element_text(colour="black", size=22),
        legend.title = element_text(size=22),
        axis.title.x=element_text(size=25),
        axis.title.y=element_text(size=25),
        axis.title.y.right = element_blank(),
        panel.grid.minor = element_line(colour="black", size=0.5),
        panel.grid.major = element_line(colour="black", size=0.5)) +
  labs(fill = "Tree Turnover (# Trees Planted)",x="ROAD",y="RUNWAY")

```


<br>

```{r message=FALSE,warning=FALSE, fig.align="center", fig.width=18, fig.height=24}


trees_final3$Column <- factor(trees_final3$Column, levels = c("A","B","C","D","E","F",
                                                              "G","H","I","J","K","L",
                                                              "M","N","O","P","Q","R","S",
                                                              "T","U","V","W","X","Y","Z","AA",
                                                              "BB","CC","DD"))


columnlabs1 <- levels(trees_final3$Column)
columnlabs2 <- c("A","B","C","D","E","F",
                 "G","H","I","J","K","L",
                 "M","N","O","P","Q","R","S",
                 "T","U","V","W","X","Y","Z","AA",
                 "BB","CC","DD")



  ggplot(filter(trees_final3, Row <= 58), aes(as.numeric(Column), Row)) + geom_tile(aes(fill = as.factor(tree_count)),colour = "white",size=2.2) +
  scale_fill_brewer(palette = "YlOrRd",type="seq") + 
  theme_minimal()  +
  scale_x_continuous(breaks = 1:length(columnlabs1),
                     labels = columnlabs1,
                     sec.axis = sec_axis(~.,
                                         breaks = 1:length(columnlabs2),
                                         labels = columnlabs2)) + 
  scale_y_continuous(sec.axis = dup_axis(),
                     breaks = round(seq(0, max(trees_final3$Row), by = 5),1),
                     minor_break = seq(0,max(trees_final3$Row),5)) + 
  theme(legend.position="top") +
  theme(axis.text.x = element_text(size =22),
        axis.text.y = element_text(size=22),
        legend.text = element_text(colour="black", size=22),
        legend.title = element_text(size=22),
        axis.title.x=element_text(size=25),
        axis.title.y=element_text(size=25),
        axis.title.y.right = element_blank(),
        panel.grid.minor = element_line(colour="black", size=0.5),
        panel.grid.major = element_line(colour="black", size=0.5)) +
  labs(fill = "Tree Turnover (# Trees Planted)",x="ROAD",y="RUNWAY")

```
